#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, platform, subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
from common import *

FILES=["scripts/phase6/common.py","scripts/phase6/capture_storage_layout.py","scripts/phase6/capture_gguf_demand_parity.py","scripts/phase6/run_storage_lifecycle.py","scripts/phase6/capture_validation_results.py","scripts/phase6/build_phase6_manifest.py","scripts/phase6/verify_phase6.py","schemas/phase6/phase6-manifest-v1.schema.json","tests/phase6/test_phase6_evidence.py","results/2026-07-30/skynet/phase6-gguf-storage/storage-layout.json","results/2026-07-30/skynet/phase6-gguf-storage/gguf-demand-parity.json","results/2026-07-30/skynet/phase6-gguf-storage/lifecycle-and-failures.json","results/2026-07-30/skynet/phase6-gguf-storage/validation-results.json","results/2026-07-30/skynet/phase6-gguf-storage/PHASE6.md","PLAN.md","docs/STATUS.md","docs/plan/04-cache-and-storage.md","docs/MODELS_AND_VALIDATION.md","docs/REPOSITORIES_AND_ARTIFACTS.md"]
def main():
 p=argparse.ArgumentParser(); p.add_argument("--project-root",type=Path,required=True); p.add_argument("--results-root",type=Path,required=True); p.add_argument("--output",type=Path,required=True); a=p.parse_args(); root=a.project_root.resolve(); rr=a.results_root.resolve()
 evidence={k:json.loads((rr/f).read_text()) for k,f in {"layout":"storage-layout.json","parity":"gguf-demand-parity.json","lifecycle":"lifecycle-and-failures.json","validation":"validation-results.json"}.items()}
 if any(x["status"]!="pass" for x in evidence.values()): raise RuntimeError("evidence failure")
 nested=git(root/"llama.cpp","rev-parse","HEAD"); gitlink=git(root,"rev-parse","HEAD:llama.cpp")
 phase5=identity(root,root/PHASE5_MANIFEST)
 models=[identity(root,root/"models/gguf/Kimi-K3-0.40B-F16.gguf"),identity(root,root/"models/gguf/Kimi-K3-0.40B-MXFP4.gguf")]
 manifest={"schema_version":"phase6-manifest-v1","closeout_state":"final-review-candidate","execution_profile":"STANDARD","issue":{"repository":"murillo128/k3-out-of-core","number":22},"revisions":{"project_execution_base":PROJECT_BASE,"project_evidence_head":git(root,"rev-parse","HEAD"),"llama_cpp_base":LLAMA_BASE,"llama_cpp_candidate":nested,"gitlink":gitlink},"checkpoint_a":{"comment_id":CHECKPOINT_COMMENT,"verdict":"PASS","safety_to_proceed":"YES","project_head":CHECKPOINT_PROJECT,"llama_cpp_head":CHECKPOINT_LLAMA,"independent_read_only":True},"phase5_input":phase5,"models":models,"generated_splits":evidence["layout"]["splits"],"environment":{"host":platform.node(),"os":platform.platform(),"filesystem":filesystem(rr),"cuda":subprocess.run(["nvidia-smi","--query-gpu=name,driver_version,memory.total","--format=csv,noheader"],text=True,capture_output=True).stdout.strip()},"evidence":{name:identity(root,rr/file) for name,file in {"storage_layout":"storage-layout.json","demand_parity":"gguf-demand-parity.json","lifecycle":"lifecycle-and-failures.json","validation":"validation-results.json"}.items()},"validation":evidence["validation"]["commands"],"gates":{"original_and_split_parity":True,"metadata_only_routed":True,"split_cross_file_bundles":True,"cold_hit_eviction_reread":True,"byte_integrity":True,"fault_cleanup_retry":True,"bounded_resources":True,"warm_captures":True,"prior_modes":True},"deferred":["direct I/O and asynchronous queueing","Phase 7 overlap and prefetch","Phase 8 CPU fallback","concurrent cached submissions, UMA, and multi-GPU"],"carried_notes":["Fixed ordinary-prompt tokenizer limitation remains visible.","Phase 3 standing performance remains a raw 22/24 pass under D-018.","Standing filesystem NVMe status is recorded without claiming NVMe performance."],"artifacts":[identity(root,root/x) for x in FILES]}
 schema=json.loads((root/"schemas/phase6/phase6-manifest-v1.schema.json").read_text()); Draft202012Validator.check_schema(schema); Draft202012Validator(schema).validate(manifest); write(a.output,manifest); print("PASS: phase6 manifest written")
if __name__=="__main__": raise SystemExit(main())
